#!/bin/bash
# build_apk.sh — Build a proper APK v2 package for OpenWrt 25.x / Alpine apk-tools
#
# APK v2 binary structure (three concatenated gzip streams):
#   Stream 1 — Signature  : gzip(tar(.SIGN.RSA.<keyname>.pub))   [SKIPPED for --allow-untrusted]
#   Stream 2 — Control    : gzip(tar(.PKGINFO, hook scripts))     [no trailing null-block EOT]
#   Stream 3 — Data       : gzip(tar(actual files))
#
# Usage: ./build_apk.sh [version] [arch]
#   version : e.g. 1.0.0   stored as 1.0.0-r0 per apk convention
#   arch    : e.g. all, aarch64, x86_64   default: all

set -e

# ── Config ────────────────────────────────────────────────────────────────────
PKG_NAME="luci-app-leigod-manager"
PKG_VER_BASE="${1:-1.0.0}"
PKG_VER="${PKG_VER_BASE}-r0"
PKG_ARCH="${2:-all}"
PKG_DESC="LuCI support for Leigod Accelerator Manager (fw4/nftables compatible)"
PKG_URL="https://github.com/ArlenDu/luci-leigod-manager"
PKG_MAINTAINER="Arlen Du"
PKG_DEPS="leigod-acc rpcd rpcd-mod-rpcsys luci-base"

PKG_SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="$PKG_SOURCE_DIR/dist"
BUILD_DIR="$PKG_SOURCE_DIR/.build_tmp_apk"

# ── Clean ─────────────────────────────────────────────────────────────────────
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR" "$OUTPUT_DIR"

echo "==> Building $PKG_NAME $PKG_VER ($PKG_ARCH) [APK v2 format]"

# ─────────────────────────────────────────────────────────────────────────────
# PART 1 — Stage data files
# ─────────────────────────────────────────────────────────────────────────────
DATA_DIR="$BUILD_DIR/data"
mkdir -p "$DATA_DIR"

install -d -m 0755 "$DATA_DIR/www/luci-static/resources/view/leigod"
install -m 0644 "$PKG_SOURCE_DIR/htdocs/luci-static/resources/view/leigod/"*.js \
    "$DATA_DIR/www/luci-static/resources/view/leigod/"

install -d -m 0755 "$DATA_DIR/usr/share/luci/menu.d"
install -m 0644 "$PKG_SOURCE_DIR/root/usr/share/luci/menu.d/luci-app-leigod-manager.json" \
    "$DATA_DIR/usr/share/luci/menu.d/"

install -d -m 0755 "$DATA_DIR/usr/share/rpcd/acl.d"
install -m 0644 "$PKG_SOURCE_DIR/root/usr/share/rpcd/acl.d/luci-app-leigod-manager.json" \
    "$DATA_DIR/usr/share/rpcd/acl.d/"

install -d -m 0755 "$DATA_DIR/usr/libexec/rpcd"
install -m 0755 "$PKG_SOURCE_DIR/root/usr/libexec/rpcd/leigod" \
    "$DATA_DIR/usr/libexec/rpcd/leigod"

install -d -m 0755 "$DATA_DIR/etc/init.d"
install -m 0755 "$PKG_SOURCE_DIR/root/etc/init.d/leigod-acc" \
    "$DATA_DIR/etc/init.d/leigod-acc"

install -d -m 0755 "$DATA_DIR/etc/config"
install -m 0644 "$PKG_SOURCE_DIR/root/etc/config/leigod-manager" \
    "$DATA_DIR/etc/config/leigod-manager"

install -d -m 0755 "$DATA_DIR/usr/share/luci/i18n"
if command -v po2lmo >/dev/null 2>&1; then
    for po in "$PKG_SOURCE_DIR"/po/*/luci-app-leigod-manager.po; do
        lang=$(basename "$(dirname "$po")")
        po2lmo "$po" "$DATA_DIR/usr/share/luci/i18n/${PKG_NAME}.${lang}.lmo"
        echo "    compiled i18n: $lang"
    done
else
    for po in "$PKG_SOURCE_DIR"/po/*/luci-app-leigod-manager.po; do
        lang=$(basename "$(dirname "$po")")
        install -m 0644 "$po" "$DATA_DIR/usr/share/luci/i18n/${PKG_NAME}.${lang}.po"
    done
    echo "    [NOTE] po2lmo not found — copied raw .po files"
fi

# ─────────────────────────────────────────────────────────────────────────────
# PART 2 — Compute installed size and build .PKGINFO
# ─────────────────────────────────────────────────────────────────────────────
INSTALLED_SIZE=$(find "$DATA_DIR" -type f -exec wc -c {} + 2>/dev/null | tail -1 | awk '{print $1}')
BUILD_DATE=$(date +%s)

CTRL_DIR="$BUILD_DIR/ctrl"
mkdir -p "$CTRL_DIR"

cat > "$CTRL_DIR/.PKGINFO" <<EOF
# Generated by build_apk.sh
pkgname = $PKG_NAME
pkgver = $PKG_VER
arch = $PKG_ARCH
size = $INSTALLED_SIZE
pkgdesc = $PKG_DESC
url = $PKG_URL
builddate = $BUILD_DATE
packager = $PKG_MAINTAINER
EOF
for dep in $PKG_DEPS; do
    echo "depend = $dep" >> "$CTRL_DIR/.PKGINFO"
done

# ─────────────────────────────────────────────────────────────────────────────
# PART 3 — Write hook scripts
# ─────────────────────────────────────────────────────────────────────────────
cat > "$CTRL_DIR/.post-install" <<'HOOK'
#!/bin/sh
[ -x /etc/init.d/leigod-acc ] && {
    chmod 0755 /etc/init.d/leigod-acc
    /etc/init.d/leigod-acc enable 2>/dev/null || true
}
[ -x /usr/libexec/rpcd/leigod ] && chmod 0755 /usr/libexec/rpcd/leigod
/etc/init.d/rpcd reload 2>/dev/null || true
exit 0
HOOK
chmod 0755 "$CTRL_DIR/.post-install"

cat > "$CTRL_DIR/.pre-deinstall" <<'HOOK'
#!/bin/sh
[ -x /etc/init.d/leigod-acc ] && {
    /etc/init.d/leigod-acc stop    2>/dev/null || true
    /etc/init.d/leigod-acc disable 2>/dev/null || true
}
exit 0
HOOK
chmod 0755 "$CTRL_DIR/.pre-deinstall"

# ─────────────────────────────────────────────────────────────────────────────
# PART 4 — Build control stream (gzip'd tar, no trailing EOT null-blocks)
# ─────────────────────────────────────────────────────────────────────────────
# The Alpine spec says control and signature streams are "tar segments" that
# intentionally omit the two-null-block EOF marker, so streams can be
# concatenated without gap.  We achieve this by piping raw tar bytes directly
# into gzip (bypassing the normal tar EOF flush).
#
# Portable trick: `tar -c` always appends null blocks on close. We strip the
# last 1024 bytes (= two 512-byte null blocks) before compressing.
CTRL_TAR_RAW="$BUILD_DIR/ctrl_raw.tar"
CTRL_GZ="$BUILD_DIR/control.tar.gz"

( cd "$CTRL_DIR" && tar -cf "$CTRL_TAR_RAW" .PKGINFO .post-install .pre-deinstall )

# Strip trailing two null-blocks (1024 bytes) then gzip
CTRL_TAR_SIZE=$(wc -c < "$CTRL_TAR_RAW")
TRIM_SIZE=$((CTRL_TAR_SIZE - 1024))
if [ "$TRIM_SIZE" -le 0 ]; then
    # Safety fallback: compress as-is
    gzip -9 -c "$CTRL_TAR_RAW" > "$CTRL_GZ"
else
    dd if="$CTRL_TAR_RAW" bs=1 count="$TRIM_SIZE" 2>/dev/null | gzip -9 > "$CTRL_GZ"
fi

# ─────────────────────────────────────────────────────────────────────────────
# PART 5 — Build data stream (standard gzip'd tar)
# ─────────────────────────────────────────────────────────────────────────────
DATA_GZ="$BUILD_DIR/data.tar.gz"
( cd "$DATA_DIR" && tar -czf "$DATA_GZ" . )

# ─────────────────────────────────────────────────────────────────────────────
# PART 6 — Concatenate: [control stream] + [data stream]  →  .apk
# (Signature stream is omitted; install with --allow-untrusted)
# ─────────────────────────────────────────────────────────────────────────────
APK_FILE="$OUTPUT_DIR/${PKG_NAME}_${PKG_VER_BASE}_${PKG_ARCH}.apk"
echo "==> Concatenating control.tar.gz + data.tar.gz → $(basename "$APK_FILE")"
cat "$CTRL_GZ" "$DATA_GZ" > "$APK_FILE"

# ─────────────────────────────────────────────────────────────────────────────
# PART 7 — Verify
# ─────────────────────────────────────────────────────────────────────────────
echo "==> Verifying gzip streams..."
# Count valid gzip members in the file
STREAM_COUNT=0
OFFSET=0
FILESIZE=$(wc -c < "$APK_FILE")
TMP_CHUNK="$BUILD_DIR/chunk.gz"

# Quick verification: try listing both streams with Python (available on macOS/Linux)
python3 - "$APK_FILE" <<'PYEOF'
import sys, gzip, io

path = sys.argv[1]
with open(path, 'rb') as f:
    data = f.read()

streams = []
pos = 0
while pos < len(data):
    if data[pos:pos+2] != b'\x1f\x8b':
        break
    # Find end of this gzip stream by decompressing
    buf = io.BytesIO(data[pos:])
    try:
        with gzip.GzipFile(fileobj=buf) as gz:
            content = gz.read()
        consumed = buf.tell()
        streams.append((pos, consumed, len(content)))
        pos += consumed
    except Exception as e:
        print(f"  Stream parse error at offset {pos}: {e}")
        break

print(f"  Found {len(streams)} gzip stream(s):")
for i, (off, sz, dlen) in enumerate(streams):
    label = ["control", "data", "?"][min(i, 2)]
    print(f"    Stream {i+1} ({label}): offset={off}, gz_size={sz}, data_size={dlen}")

if len(streams) >= 2:
    print("  ✅ Package structure OK (control + data streams present)")
    sys.exit(0)
else:
    print("  ❌ Expected at least 2 gzip streams")
    sys.exit(1)
PYEOF

echo "==> Control stream contents:"
zcat "$CTRL_GZ" | tar -t 2>/dev/null || true

echo "==> Data stream file tree:"
tar -tzf "$DATA_GZ" | sort

# ─────────────────────────────────────────────────────────────────────────────
# PART 8 — Cleanup & summary
# ─────────────────────────────────────────────────────────────────────────────
rm -rf "$BUILD_DIR"

SIZE=$(du -sh "$APK_FILE" | awk '{print $1}')
echo ""
echo "✅  Build successful!"
echo "    File : $APK_FILE"
echo "    Size : $SIZE"
echo ""
echo "Deploy to router (OpenWrt with apk):"
echo "    scp $APK_FILE root@<router-ip>:/tmp/"
echo "    ssh root@<router-ip> 'apk add --allow-untrusted /tmp/$(basename "$APK_FILE")'"
